#!/bin/bash
echo only run this when your done partitioning and mounting
pacstrap /mnt linux linux-firmware base base-devel grub efibootmgr networkmanager neovim qt6
arch-chroot /mnt /bin/bash <<EOF
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc
sudo pacman -S gnome
echo "hostname" > /etc/hostname
passwd root
useradd mbbOS
passwd mbbOS
pacman -S grub
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=mbbOS --removable --force --verbose
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable gdm
EOF

echo done just reboot now
